title: 推送
description: 展示推送（subscription articles）。
lang: zh-CN

domain: ydx-2147483647.github.io
url: https://ydx-2147483647.github.io
baseurl: /subs-articles
github_username: YDX-2147483647

theme: jekyll-theme-architect
show_downloads: false

plugins:
  - jekyll-feed

collections:
  articles:
    output: true
    permalink: /:name/
  slides:
    output: true
    permalink: /:collection/:path

defaults:
  - scope:
      path: ''
      type: articles
    values:
      layout: default

exclude:
  - /.vscode/
  - /README.md
